# Generated by Django 5.0.4 on 2024-05-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={},
        ),
        migrations.RemoveField(
            model_name='docente',
            name='created',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='updated',
        ),
    ]
