# Generated by Django 5.0.4 on 2024-05-01 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_alter_docente_options_remove_docente_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={},
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='created',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='updated',
        ),
    ]
