# Generated by Django 5.0.4 on 2024-05-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_alter_asignatura_options_remove_asignatura_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignatura',
        ),
    ]
