# Generated by Django 5.0.4 on 2024-05-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_delete_asignatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
