# Generated by Django 5.0.4 on 2024-05-02 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='fecha de Nacimiento'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=20, verbose_name='Apeliido Paterno')),
                ('apellido_materno', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], default='F', max_length=1)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.curso')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'db_table': 'estudiante',
            },
        ),
    ]
