# Generated by Django 5.0.4 on 2024-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_estudiante_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_seccion', models.CharField(choices=[('A', 'seccion A'), ('B', 'Seccion B'), ('C', 'seccion c'), ('D', 'seccion D')], default='-', max_length=1, verbose_name='Sección')),
                ('modalidad', models.CharField(choices=[('PR', 'PRESENCIAL'), ('SM', 'sEMIPRESENCIAL'), ('VT', 'VIRTUAL')], default='-', max_length=2)),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('duracion_clase', models.PositiveIntegerField(default=1, verbose_name='horas de clase')),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='docente',
        ),
        migrations.AddField(
            model_name='docente',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('F', 'femenino'), ('M', 'masculino')], default='-', max_length=1),
        ),
    ]
