# Generated by Django 5.0.4 on 2024-05-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0009_salon_remove_curso_docente_remove_curso_seccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'salon', 'verbose_name_plural': 'salones'},
        ),
        migrations.AlterModelTable(
            name='salon',
            table='salones',
        ),
    ]
