# Generated by Django 5.0.4 on 2024-05-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0011_remove_salon_duracion_clase_salon_duracion_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='duracion_clases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='hora_fin',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salon',
            name='modalidad',
            field=models.CharField(choices=[('PR', 'PRESENCIAL'), ('SM', 'SEMIPRESENCIAL'), ('VT', 'VIRTUAL')], default='-', max_length=2),
        ),
    ]
