# Generated by Django 5.0.4 on 2024-05-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_alter_salon_duracion_clases_alter_salon_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='hora_fin',
            field=models.TimeField(auto_created=True, blank=True, null=True),
        ),
    ]
