# Generated by Django 5.0.4 on 2024-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_alter_salon_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
