# Generated by Django 5.0.4 on 2024-05-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0014_alter_salon_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='Docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApp.docente'),
        ),
    ]
