# Generated by Django 5.0.4 on 2024-05-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_curso_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Docente',
        ),
    ]
