# Generated by Django 5.0.4 on 2024-05-03 00:28

import django.db.models.deletion
import webApp.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_remove_curso_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(validators=[webApp.choices.validate_nota])),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPreguntas', models.IntegerField(validators=[webApp.choices.validate_nota])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.docente')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.evaluaciones')),
            ],
        ),
        migrations.DeleteModel(
            name='salon',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.evaluaciones'),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webApp.pregunta'),
        ),
    ]
