# Generated by Django 5.0.4 on 2024-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0017_calificaciones_evaluaciones_opcionrespuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantErrorFacial', models.IntegerField()),
                ('porcenComportamiento', models.FloatField()),
                ('tiempoPromedio', models.TimeField()),
                ('tiempoPorPregunta', models.TimeField()),
                ('porcenPlagioTotal', models.FloatField()),
            ],
        ),
    ]
