# Generated by Django 5.0.4 on 2024-05-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0018_monitoreoexamen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcionrespuesta',
            old_name='texto',
            new_name='respuesta',
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='opcion',
            field=models.CharField(choices=[('A', 'opcion A'), ('B', 'opcion B'), ('C', 'opcion C'), ('D', 'Opcion D')], default='-', max_length=1),
        ),
        migrations.AlterField(
            model_name='monitoreoexamen',
            name='cantErrorFacial',
            field=models.IntegerField(verbose_name='errores faciales'),
        ),
        migrations.AlterField(
            model_name='monitoreoexamen',
            name='porcenComportamiento',
            field=models.FloatField(verbose_name='comp sospechoso'),
        ),
        migrations.AlterField(
            model_name='monitoreoexamen',
            name='porcenPlagioTotal',
            field=models.FloatField(verbose_name='porcentaje plagio'),
        ),
        migrations.AlterField(
            model_name='monitoreoexamen',
            name='tiempoPorPregunta',
            field=models.TimeField(verbose_name='tiempo pregunta'),
        ),
        migrations.AlterField(
            model_name='monitoreoexamen',
            name='tiempoPromedio',
            field=models.TimeField(verbose_name='tiempo examen'),
        ),
    ]
