# Generated by Django 5.0.4 on 2024-05-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0020_alter_opcionrespuesta_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='nombre_Evaluacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
