# Generated by Django 5.0.4 on 2024-05-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0021_evaluaciones_nombre_evaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluaciones',
            options={'verbose_name': 'evaluacion', 'verbose_name_plural': 'evaluaciones'},
        ),
        migrations.AlterModelTable(
            name='evaluaciones',
            table='evaluaciones',
        ),
    ]
