# Generated by Django 5.0.4 on 2024-05-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0023_alter_pregunta_options_alter_pregunta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreoexamen',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webApp.estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoreoexamen',
            name='evaluacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='webApp.evaluaciones'),
            preserve_default=False,
        ),
    ]
