# Generated by Django 5.0.4 on 2024-05-30 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0024_monitoreoexamen_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='webApp.docente'),
            preserve_default=False,
        ),
    ]
