# Generated by Django 5.0.4 on 2024-05-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0028_rename_usuario_docente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificaciones',
            old_name='examen',
            new_name='evaluacion',
        ),
    ]
