# Generated by Django 5.0.4 on 2024-06-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0029_rename_examen_calificaciones_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='duracion',
            field=models.IntegerField(blank=True, help_text='Duración del examen en minutos', null=True),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
