# Generated by Django 5.0.4 on 2024-06-03 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0030_evaluaciones_duracion_evaluaciones_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('A', 'opcion A'), ('B', 'opcion B'), ('C', 'opcion C'), ('D', 'Opcion D')], max_length=1)),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_correcta', to='webApp.pregunta')),
            ],
            options={
                'verbose_name': 'respuesta_correcta',
                'verbose_name_plural': 'respuestas_correctas',
                'db_table': 'respuestas_correctas',
            },
        ),
    ]
