# Generated by Django 5.0.4 on 2024-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0032_alter_opcionrespuesta_opcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionrespuesta',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
    ]
