# Generated by Django 5.0.4 on 2024-06-03 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0035_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'opcion', 'verbose_name_plural': 'opciones'},
        ),
        migrations.AlterModelTable(
            name='opcionrespuesta',
            table='opciones_examen',
        ),
    ]
