# Generated by Django 5.0.4 on 2024-06-03 04:22

import webApp.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0036_alter_opcionrespuesta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='puntos',
            field=models.FloatField(default=0, validators=[webApp.choices.validate_nota]),
        ),
    ]
