# Generated by Django 5.0.4 on 2024-06-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0038_alter_monitoreoexamen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/'),
        ),
    ]
