# Generated by Django 5.0.4 on 2024-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0039_estudiante_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(default='fotos_estudiantes/default.png', upload_to='fotos_estudiantes/', verbose_name='foto'),
        ),
    ]
